//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AleCGN.Security.Cryptography.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LibraryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AleCGN.Security.Cryptography.Resources.LibraryResources", typeof(LibraryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AES key..
        /// </summary>
        internal static string Validation_AESKey {
            get {
                return ResourceManager.GetString("Validation_AESKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES key not set; When instantiating this class with the constructor without the AES key, the SetOrUpdateKey(...) method must be called imediatelly before encrypting or decrypting data, providing a valid AES key..
        /// </summary>
        internal static string Validation_AESKeyNotSet {
            get {
                return ResourceManager.GetString("Validation_AESKeyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; cannot be null or 0 length..
        /// </summary>
        internal static string Validation_ArgumentDataNullOrZeroLength {
            get {
                return ResourceManager.GetString("Validation_ArgumentDataNullOrZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; with value out of range, verify..
        /// </summary>
        internal static string Validation_ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("Validation_ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; cannot be null, empty or whitespace..
        /// </summary>
        internal static string Validation_ArgumentStringNullEmpytOrWhitespace {
            get {
                return ResourceManager.GetString("Validation_ArgumentStringNullEmpytOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string Validation_FileNotFound {
            get {
                return ResourceManager.GetString("Validation_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is not a valid base64 string..
        /// </summary>
        internal static string Validation_InvalidBase64String {
            get {
                return ResourceManager.GetString("Validation_InvalidBase64String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is not a valid hexadecimal string..
        /// </summary>
        internal static string Validation_InvalidHexadecimalString {
            get {
                return ResourceManager.GetString("Validation_InvalidHexadecimalString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must be at least 8 bytes long (RFC 8018)..
        /// </summary>
        internal static string Validation_Pbkdf2SaltSize {
            get {
                return ResourceManager.GetString("Validation_Pbkdf2SaltSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is not a valid base32 string..
        /// </summary>
        internal static string Validation_InvalidBase32String {
            get {
                return ResourceManager.GetString("Validation_InvalidBase32String", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid key (wrong size/length) for the selected algorithm..
        /// </summary>
        internal static string Validation_InvalidKey {
            get {
                return ResourceManager.GetString("Validation_InvalidKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key not set; when instantiating this class with the constructor without a key, the SetOrUpdateKey(...) method must be called before performing any operation, providing a valid key..
        /// </summary>
        internal static string Validation_KeyNotSet {
            get {
                return ResourceManager.GetString("Validation_KeyNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is not a valid password hash string..
        /// </summary>
        internal static string Validation_InvalidPasswordHash {
            get {
                return ResourceManager.GetString("Validation_InvalidPasswordHash", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The encrypted payload format is not valid or the data is corrupted..
        /// </summary>
        internal static string Validation_InvalidPayloadFormat {
            get {
                return ResourceManager.GetString("Validation_InvalidPayloadFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is not a valid PEM-encoded key..
        /// </summary>
        internal static string Validation_InvalidPemKey {
            get {
                return ResourceManager.GetString("Validation_InvalidPemKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Public key not set; provide a PEM-encoded public key in the constructor to perform this operation..
        /// </summary>
        internal static string Validation_PublicKeyNotSet {
            get {
                return ResourceManager.GetString("Validation_PublicKeyNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Private key not set; provide a PEM-encoded private key in the constructor to perform this operation..
        /// </summary>
        internal static string Validation_PrivateKeyNotSet {
            get {
                return ResourceManager.GetString("Validation_PrivateKeyNotSet", resourceCulture);
            }
        }
    }
}
