using AleCGN.Security.Cryptography.Resources;
using static AleCGN.Security.Cryptography.Helpers.ExceptionHelper;

namespace AleCGN.Security.Cryptography.KeyDerivation
{
    public class Argon2idConfiguration
    {
        // OWASP-recommended defaults: 19 MiB of memory, 2 iterations, 1 degree of parallelism.
        private const int _defaultMemorySizeInKB = 19_456;
        private const int _defaultIterations = 2;
        private const int _defaultParallelism = 1;
        private const int _defaultSaltSize = 16;
        private const int _defaultDerivedKeySize = 32;

        public Argon2idConfiguration(
            int memorySizeInKB,
            int iterations,
            int parallelism,
            int saltSize,
            int derivedKeySize)
        {
            if (memorySizeInKB <= 0)
            {
                ThrowFormattedArgumentException(LibraryResources.Validation_ArgumentOutOfRange, nameof(memorySizeInKB));
            }

            if (iterations <= 0)
            {
                ThrowFormattedArgumentException(LibraryResources.Validation_ArgumentOutOfRange, nameof(iterations));
            }

            if (parallelism <= 0)
            {
                ThrowFormattedArgumentException(LibraryResources.Validation_ArgumentOutOfRange, nameof(parallelism));
            }

            if (saltSize < Pbkdf2Configuration.MinimumSaltSize)
            {
                ThrowFormattedArgumentException(LibraryResources.Validation_Pbkdf2SaltSize, nameof(saltSize));
            }

            if (derivedKeySize <= 0)
            {
                ThrowFormattedArgumentException(LibraryResources.Validation_ArgumentOutOfRange, nameof(derivedKeySize));
            }

            MemorySizeInKB = memorySizeInKB;
            Iterations = iterations;
            Parallelism = parallelism;
            SaltSize = saltSize;
            DerivedKeySize = derivedKeySize;
        }


        public int MemorySizeInKB { get; }

        public int Iterations { get; }

        public int Parallelism { get; }

        /// <summary>
        /// Size in bytes of the salt generated by the DeriveKey/DeriveTextKey overloads that create a random salt.
        /// </summary>
        public int SaltSize { get; }

        /// <summary>
        /// Size in bytes of the derived key.
        /// </summary>
        public int DerivedKeySize { get; }


        /// <summary>
        /// Argon2id with 19 MiB of memory, 2 iterations and parallelism 1 (OWASP recommendation),
        /// 16-byte salt and 32-byte derived key.
        /// </summary>
        public static Argon2idConfiguration Default
            => new Argon2idConfiguration(
                _defaultMemorySizeInKB,
                _defaultIterations,
                _defaultParallelism,
                _defaultSaltSize,
                _defaultDerivedKeySize);
    }
}
