using AleCGN.Security.Cryptography.Resources;
using static AleCGN.Security.Cryptography.Helpers.ExceptionHelper;

namespace AleCGN.Security.Cryptography.KeyDerivation
{
    public class Pbkdf2Configuration
    {
        // RFC 8018 recommends a salt of at least 64 bits.
        internal const int MinimumSaltSize = 8;

        private const Pbkdf2PseudoRandomFunction _defaultPseudoRandomFunction = Pbkdf2PseudoRandomFunction.HMACSHA256;
        private const int _defaultIterations = 600_000;
        private const int _defaultSaltSize = 16;
        private const int _defaultDerivedKeySize = 32;

        public Pbkdf2Configuration(
            Pbkdf2PseudoRandomFunction pseudoRandomFunction,
            int iterations,
            int saltSize,
            int derivedKeySize)
        {
            if (iterations <= 0)
            {
                ThrowFormattedArgumentException(LibraryResources.Validation_ArgumentOutOfRange, nameof(iterations));
            }

            if (saltSize < MinimumSaltSize)
            {
                ThrowFormattedArgumentException(LibraryResources.Validation_Pbkdf2SaltSize, nameof(saltSize));
            }

            if (derivedKeySize <= 0)
            {
                ThrowFormattedArgumentException(LibraryResources.Validation_ArgumentOutOfRange, nameof(derivedKeySize));
            }

            PseudoRandomFunction = pseudoRandomFunction;
            Iterations = iterations;
            SaltSize = saltSize;
            DerivedKeySize = derivedKeySize;
        }


        public Pbkdf2PseudoRandomFunction PseudoRandomFunction { get; }

        public int Iterations { get; }

        /// <summary>
        /// Size in bytes of the salt generated by the DeriveKey/DeriveTextKey overloads that create a random salt.
        /// </summary>
        public int SaltSize { get; }

        /// <summary>
        /// Size in bytes of the derived key.
        /// </summary>
        public int DerivedKeySize { get; }


        /// <summary>
        /// PBKDF2-HMAC-SHA256 with 600,000 iterations (OWASP recommendation), 16-byte salt and 32-byte derived key.
        /// </summary>
        public static Pbkdf2Configuration Default
            => new Pbkdf2Configuration(_defaultPseudoRandomFunction, _defaultIterations, _defaultSaltSize, _defaultDerivedKeySize);
    }
}
